version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    versions:
      applies-to: version-updates
      update-types: 
      - minor
      - patch
  assignees:
  - "nu12"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
  assignees:
  - "nu12"